### ISSUE TITLE
Server hang on shutdown

### ISSUE THREAD

**Issue by Q7Sa** [qixils/depiglining#1]
I have a Fabric 1.16.5 server and have done binary elimination and discovered that Depiglining is causing it somehow.

How to reproduce:
Install the Fabric server and Depiglining, then run the server to create a world then stop it. The server will freeze until its forcebly closed.

**Comment by qixils** [comment]
Found the issue, just gotta watch for server stop and close a few resources. Just need to test my fix on forge then will push out an update.

**Comment by qixils** [comment]
Fixed by https://github.com/qixils/depiglining/releases/tag/v1.0.1, thank you for reporting!
